{% set name = "blp" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/blp/blp-{{ version }}.tar.gz
  sha256: 2c02a6a64640ef351577c1b006505cd2af6dbe290c7884d1b7918c812ef8827d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas
    - python >=3.6
    - blpapi

test:
  imports:
    - blp

about:
  home: https://github.com/matthewgilbert/blp
  license: Apache-2.0
  license_file: LICENSE
  summary: Pythonic interface to Bloomberg Open API

extra:
  recipe-maintainers:
    - matthewgilbert
