{% set name = "blp" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blp/blp-{{ version }}.tar.gz
  sha256: b025e9f58c47ef383132b9718e463de6c1274b61773c52f2b4cb9f340b9ee62f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas
    - python >=3.6
    - blpapi

test:
  imports:
    - blp

about:
  home: https://github.com/matthewgilbert/blp
  license: Apache-2.0
  license_file: LICENSE
  summary: Pythonic interface to Bloomberg Open API

extra:
  recipe-maintainers:
    - matthewgilbert
