{% set name = "blp" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blp/blp-{{ version }}.tar.gz
  sha256: 094c09b05fb006769f48309588f4200d593299b58566d03e6a188c16296cd98f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pandas
    - python >=3.6
    - blpapi

test:
  imports:
    - blp

about:
  home: https://github.com/matthewgilbert/blp
  license: Apache-2.0
  license_file: LICENSE
  summary: Pythonic interface to Bloomberg Open API

extra:
  recipe-maintainers:
    - matthewgilbert
